name: uni
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:

  - matplotlib=3.9.2=py311haa95532_0
  - matplotlib-base=3.9.2=py311h472561b_0
  - matplotlib-inline=0.1.6=py311haa95532_0
  - pandas=2.2.2=py311hea22821_0
  - voila=0.5.7=py311haa95532_0
  - pip:
      - jsonschema-specifications==2024.10.1
      - jupyterlab-pygments==0.3.0
      - mistune==3.0.2
      - unicodecsv==0.14.1
      - yarg==0.1.9
